### ISSUE TITLE
conda-build > 3.5.1 can't build epics-base

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-recipes#3]
To be investigated later... Something bad happens in newer versions of `conda-build` that breaks `epics-base` builds to the point where `caget -h` can't even run. It looks like the `rpath` magic that `conda` does encounters tons of permission errors, preventing the library from installing correctly.

For now, this is a reminder to self to not update my `conda-build` version until I have time to resolve this.

**Comment by teddyrendahl** [comment]
😱 Is this our `epics-base` recipe or the community?

**Comment by ZLLentz** [comment]
Both. Ours it basically the same as everyone else's, and I'm swapping to be the exactly the same as nsls-ii.
